spring:
  application:
    name: kkbmsc-consumer-depart #指定微服务对外暴露的名称
eureka:
  client:
    service-url: #暴露服务中心地址
      defaultZone: http://localhost:8000/eureka
#      开启feign对hystrix的支持
feign:
  hystrix:
    enabled: false
#    设置服务熔断时限 默认为5000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
